services:
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=https://theopensourcehelper.tech/api
    dns:
      - 8.8.8.8
      - 8.8.4.4
       
    
    ports:
      - "80:80"
      - "443:443"
    volumes:
       - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
       - /etc/letsencrypt:/etc/letsencrypt:ro
       - /var/lib/letsencrypt:/var/lib/letsencrypt:ro
    depends_on:
      - backend
 
  backend:
    build: ./backend
    
    expose:
      - "4000"   
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/opensource-db
      - REDIS_HOST=redis
      - GEMINI_API_KEY=${GEMINI_API_KEY}
   
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_started

  mongodb:
    image: mongo:7.0
    container_name: helper-db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongo-data:/data/db
 
  redis:
    image: redis:alpine
    container_name: helper-cache
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data: