 
gzip on;
gzip_comp_level 6;
gzip_vary on;

upstream backend_servers {
    server backend:4000;  
    keepalive 64;
}

server {
    listen 80;
    error_page 502 /502.html;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

   
    location /api/ {
        proxy_pass http://backend_servers/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
    }
}